---

- name: install sshguard
  package:
    name: '{{ sshguard_packages }}'
    state: 'present'
  register: t_sshguard_install

- name: configure sshguard
  debug:
    msg: "FIXME"

- name: activate service
  block:
    - name: activate service on FreeBSD
      block:
        - include: sysrc.yml entry="{{ sshguard_sysrc }}"
          loop: "{{ sshguard_sysrcs }}"
          loop_control:
            loop_var: sshguard_sysrc

        - service:
            name: "{{ sshguard_service }}"
            state: started
          register: t_sshguard_service

        - service:
            name: "{{ sshguard_service }}"
            state: restarted
          when: t_sshguard_config.changed and not t_sshguard_service.changed

      when: ansible_distribution == 'FreeBSD'
